#!/bin/bash

# Obtener el hostname del servidor
hostname=$(hostname)

# Definir los nombres de los archivos
archivo1="archivo_servidor1.txt"
archivo2="archivo_servidor2.txt"
archivo3="archivo_servidor3.txt"

# Verificar el hostname y realizar acciones según corresponda
case $hostname in
    "servidor1")
        cp $archivo1 /destino/
        rm $archivo2 $archivo3
        ;;
    "servidor2")
        cp $archivo2 /destino/
        rm $archivo1 $archivo3
        ;;
    "servidor3")
        cp $archivo3 /destino/
        rm $archivo1 $archivo2
        ;;
    *)
        echo "Hostname desconocido: $hostname"
        exit 1
        ;;
esac
